### ISSUE TITLE
data for PS 2.6

### ISSUE THREAD

**Issue by shivmeev** [haroldmei/MLAI#1]
I have been reviewing your solution for CS229. Thanks for uploading them here. 
I was wondering if you can possibly upload data for PS 2.6. I cannot access it anymore through CS229 webpage. I really appreciate it.

**Comment by haroldmei** [comment]
@shivmeev have you found the data for PS2.6? Sorry I wasn't aware of the issue you raised here. :)
Let me know if you still need help.
Harold.

**Comment by haroldmei** [comment]
Looks you've got the data, close the issue.

**Comment by shivmeev** [comment]
Oh sorry Harold for not getting back to you earlier.
Yes, I do have the data, but thanks so much for your follow up!
